name: 'Kubernetes Set Context'
description: 'Set the context of a target Kubernetes cluster and export the kubeconfig which is used by subsequent actions'
inputs:
   # Please ensure you have used azure/login in the workflow before this action
   cluster-type:
      description: 'Acceptable values: generic or arc'
      required: false
      default: 'generic'
   method:
      description: 'Acceptable values: kubeconfig or service-account or service-principal'
      required: false
      default: 'kubeconfig'
   kubeconfig:
      description: 'Contents of kubeconfig file'
      required: false
   context:
      description: 'If your kubeconfig has multiple contexts, use this field to use a specific context, otherwise the default one would be chosen'
      required: false
   k8s-url:
      description: 'Cluster Url'
      required: false
   k8s-secret:
      description: 'Service account secret (run kubectl get serviceaccounts <service-account-name> -o yaml and copy the service-account-secret-name)'
      required: false
   token:
      description: 'Token extracted from the secret of service account (should be base 64 decoded)'
      required: false
   resource-group:
      description: 'Azure resource group name. Required for az cli approach'
      required: false
   cluster-name:
      description: 'Azure connected cluster name. Required for az cli approach'
      required: false
   use-kubelogin:
      description: 'Enables kubelogin for non-admin user scenario. Required for non-admin az cli approach. Acceptable values: true or false'
      default: 'false'
      required: false
   admin:
      description: 'Get cluster admin credentials. Required for az cli approach. Acceptable values: true or false'
      default: 'false'
      required: false
   use-az-set-context:
      description: 'Use az cli to get kubeconfig and set context. Acceptable values: true or false'
      default: 'false'
      required: true
branding:
   color: 'blue'
runs:
   using: 'node16'
   main: 'lib/index.js'
