name: Bug Report
description: File a bug report, we will respond to this thread with any questions.
title: 'Bug: '
labels: ['bug', 'triage']
assignees:
   - Azure/aks-atlanta
body:
   - type: input
     id: what-happened
     attributes:
        label: what happened?
        description: also tell us what did you expect to happen?
        placeholder: tell us what you see!
     validations:
        required: true
   - type: input
     id: version
     attributes:
        label: version
        description: what action version are you running?
        placeholder: mention the action version
     validations:
        required: true
   - type: input
     id: runner
     attributes:
        label: runner
        description: what runner are you using?
        placeholder: mention the runner(self-hosted, operating system)
     validations:
        required: true
   - type: input
     id: logs
     attributes:
        label: relevant log output
        description: run in debug mode for the most verbose logs. Please feel free to attach a screenshot of the logs
        render: shell
   - type: checkboxes
     id: terms
     attributes:
        label: code of Conduct
        description: by submitting this issue, you agree to follow our [Code of Conduct]()
        options:
           - label: I agree to follow this project's Code of Conduct
             required: true
