apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRWyUSUZJQ
  namespace: ZGVmBXUsLdA==
  token: ZXlKaGJHY2lPcUpTVXpJMU5pSX=
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: e1414a3z-22fe-48d1-ab9e-18e4a5b91c
  creationTimestamp: "2020-03-02T06:40:31Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:namespace: {}
        f:token: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/service-account.name: {}
          f:kubernetes.io/service-account.uid: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-03-02T06:40:31Z"
  name: default-token-bl8ra
  namespace: default
  resourceVersion: "278"
  selfLink: /api/v1/namespaces/default/secrets/default-token-bl8ra
  uid: e6d8b21b-2e3a-4606-98za-54fb44fdc
type: kubernetes.io/service-account-token
