name: Check Signed Commits

on:
   pull_request:

permissions:
   contents: read
   pull-requests: write

jobs:
   signed:
      uses: Azure/action-release-workflows/.github/workflows/check_signed_commits.yaml@2ff084415c5af591fd13d95ddbfc4cdb5ed2012e
