# This is a basic workflow to help you get started with Actions

name: k8s-set-context

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ cluster-connect-2 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: atharvamulmuley/k8s-set-context@cluster-connect-2
        with:
          method: 'SPN'
          cluster-type: 'arc'
          creds: '${{ secrets.AZURE_CREDS }}'
          cluster-name: arcaction
          resource-group: atharvatest2
          token: '${{ secrets.SA_TOKEN }}'
      - run: |
          kubectl get pods -A
  build-2:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: atharvamulmuley/k8s-set-context@cluster-connect-2
        with:
          method: 'SPN'
          cluster-type: 'arc'
          creds: '${{ secrets.AZURE_CREDS }}'
          cluster-name: arcaction
          resource-group: atharvatest2
          token: '${{ secrets.SA_TOKEN }}'
      - run: |
          kubectl get pods -A