name: 'Run prettify'
on:
   pull_request:
   push:
      branches: [main]

jobs:
   prettier:
      name: Prettier Check
      runs-on: ubuntu-latest
      steps:
         - name: Checkout Repository
           uses: actions/checkout@v4

         - name: Enforce Prettier
           uses: actionsx/prettier@3d9f7c3fa44c9cb819e68292a328d7f4384be206 #v3.0.0
           with:
              args: --check .
